---
service: spp-rsi-lambda-scripts
provider:
  name: aws
  deploymentBucket:
    name: spp-results-${self:custom.environment}-serverless
  role: arn:aws:iam::#{AWS::AccountId}:role/lambda_invoke_lambda
  vpc:
    securityGroupIds:
      - ${file(../json_outputs/security_groups_output.json):SecurityGroups.0.GroupId}
    subnetIds:
      - ${file(../json_outputs/subnets_output.json):Subnets.0.SubnetId}
      - ${file(../json_outputs/subnets_output.json):Subnets.1.SubnetId}
  runtime: python3.7
  region: eu-west-2
  package:
    individually: true
  memorySize: 512
  timeout: 10
  tracing:
    lambda: true

custom:
  environment: ${env:ENVIRONMENT}

functions:
  deploy-dynamo-query-runner:
    name: spp-res_lam_dynamodb_queryrunner
    handler: dynamo_queryrunner.lambda_handler
    package:
      include:
        - dynamo_queryrunner/dynamo_queryrunner.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:#{AWS::AccountId}:layer:es_python_layer:latest
      - arn:aws:lambda:eu-west-2:#{AWS::AccountId}:layer:dev-es-common-functions:latest
    tags:
      app: results
    environment:
      table_name: spp_res_ddb_templates

  deploy-glue-runner:
    name: spp-res_lam_glue_runner
    handler: gluerunner.lambda_handler
    package:
      include:
        - gluerunner/gluerunner.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:#{AWS::AccountId}:layer:es_python_layer:latest
      - arn:aws:lambda:eu-west-2:#{AWS::AccountId}:layer:dev-es-common-functions:latest
    tags:
      app: results
    environment:
      environment: ${env:ENVIRONMENT}
      # yamllint disable-line rule:line-length
      sfn_activity_arn: arn:aws:states:eu-west-2:#{AWS::AccountId}:activity:spp-res_sfn_GlueRunnerActivity
      sfn_worker_name: spp-res_lam_glue_runner
      ddb_table: spp-res_ddb_GlueRunnerActiveJobs
      ddb_query_limit: 50
      spark_glue_job_capacity: 1


  deploy-step-runner:
    name: spp-res_lam_step_runner
    handler: steprunner.lambda_handler
    package:
      include:
        - steprunner/steprunner.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:#{AWS::AccountId}:layer:es_python_layer:latest
      - arn:aws:lambda:eu-west-2:#{AWS::AccountId}:layer:dev-es-common-functions:latest
    tags:
      app: results
    environment:
      environment: ${env:ENVIRONMENT}
      glue_emr_job_name: spp-res_glu_emr
      glue_pyshell_job_name: spp-res_glu_pyshell
      # yamllint disable-line rule:line-length
      sfn_glue_name: arn:aws:states:eu-west-2:#{AWS::AccountId}:stateMachine:spp-res_sfn_glue

plugins:
  - serverless-latest-layer-version
  - serverless-pseudo-parameters
