---
service: spp-rsi-lambda-scripts
provider:
  name: aws
  deploymentBucket:
    name: spp-results-${self:custom.environment}-serverless
  role: arn:aws:iam::#{AWS::AccountId}:role/spp-res_Role_Lambda
  runtime: python3.7
  region: eu-west-2
  package:
    individually: true
  memorySize: 512
  timeout: 10
  tracing:
    lambda: true

custom:
  environment: ${env:ENVIRONMENT}

functions:
  deploy-dynamo-query-runner:
    name: spp-res_lam_dynamodb_queryrunner
    handler: dynamo_queryrunner/dynamo_queryrunner.lambda_handler
    package:
      include:
        - dynamo_queryrunner/dynamo_queryrunner.py
      exclude:
        - ./**
      individually: true
    layers:
      - arn:aws:lambda:eu-west-2:#{AWS::AccountId}:layer:es_python_layer:latest
      - arn:aws:lambda:eu-west-2:#{AWS::AccountId}:layer:dev-es-common-functions:latest
    tags:
      app: results
    environment:
      table_name: spp_res_ddb_templates

  deploy-glue-runner:
    name: spp-res_lam_glue_runner
    handler: gluerunner/gluerunner.handler
    timeout: 300
    events:
      - cloudwatchEvent:
          name: 'glu_emr_trigger_event'
          event:
            source:
              - 'aws.glue'
            detail-type:
              - 'Glue Job State Change'
            detail:
              jobName:
                - 'spp-res_glu_emr'
      - cloudwatchEvent:
          name: 'glu_ingest_trigger_event'
          event:
            source:
              - 'aws.glue'
            detail-type:
              - 'Glue Job State Change'
            detail:
              jobName:
                - 'spp-res_glu_ingest'
    package:
      include:
        - gluerunner/gluerunner.py
      exclude:
        - ./**
      individually: true
    layers:
      - arn:aws:lambda:eu-west-2:#{AWS::AccountId}:layer:es_python_layer:latest
      - arn:aws:lambda:eu-west-2:#{AWS::AccountId}:layer:dev-es-common-functions:latest
    tags:
      app: results
    environment:
      environment: ${env:ENVIRONMENT}
      spark_glue_job_capacity: 1
      ingest_glue_name: spp-res_glu_ingest
      emr_glue_name: spp-res_glu_emr

plugins:
  - serverless-latest-layer-version
  - serverless-pseudo-parameters
